before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.56.1/hugo_0.56.1_Linux-64bit.tar.gz
  - tar -xzvf hugo_0.56.1_Linux-64bit.tar.gz
  - chmod +x hugo
  - export PATH=$PATH:$PWD
  - hugo version

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public/
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: master
  on:
    branch: dev