# Site

baseurl: ''
url: 'https://matq007.github.io'

# Plugins
plugins: 
  - jekyll-paginate
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge

include:
  - "_pages"