# Site

baseurl: ''
url: 'https://github.com/matq007/matq007.github.io'

# Plugins
plugins: 
  - jekyll-paginate
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
