# Website setup

baseURL = "https://matq007.github.io"
languageCode = "en-us"
title = "Martin Proks (@mproksik)"
theme = "monkey"
googleAnalytics = "UA-148477750-1"
disqusShortname = "http-matq007-github-io"

[author]  
  name = "Martin Proks" 
  bio = "Bioinformatician"

[menu]
    [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

    [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

    [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4

[taxonomies]
  tag = "tags"
