# Website setup

baseURL = "/"
languageCode = "en-us"
title = "Martin Proks (@mproksik)"
theme = "monkey"

[menu]

    [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

    [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 2

    [[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

    [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4
